### ISSUE TITLE
Sort by importance button

### ISSUE THREAD

**Issue by john9hoff** [UMM-CSci/URSAmajor#5]
Under the Submission List tab, there are three options where you can choose:

Sort by importance
Sort by newest
Sort by oldest

The latter two work fine, but sort by importance doesn't do anything. It might sort by newest, but that doesn't really make them more or less important. How do you want to do this?

**Comment by smil1201** [comment]
Upon delving further into the functionality of this sort method, it appears that sort by importance is arranging the submissions according to their existing review vote information. It is taking the accepted votes for accepted, minor changes, major changes, and total rewrite, then turning those values into a weight which designates the degree to which that submission is in need of attention. I am assuming this was the method that the client asked for so I will leave it as is, however it may need revisiting if the client finds it confusing or in need of re-balancing.
